language: csharp
dotnet: 2.0.0
sudo: required
dist: trusty
env:
#- PGUSER=postgres
#- POSTGRES_PASSWORD=skhokho
before_script:
  #- sudo apt-get install postgresql-9.4-plv8 -y
  #- psql -c 'create database idsrv4_test;' -U postgres
  #- psql -d idsrv4_test -U postgres -c "create extension if not exists plv8;"
  
addons:
  postgresql: "9.4"
  apt:
    packages:
    
script: 
    - curl https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 3.1.101
    - if test "$TRAVIS_OS_NAME" == "linux"; then export PATH="/home/travis/.dotnet":"$PATH"; fi
    - if test "$TRAVIS_OS_NAME" == "osx"; then export PATH="/Users/travis/.dotnet":"$PATH"; fi
    - chmod +x build.sh
    #- ./build.sh
    - dotnet restore
    - dotnet build
    
notifications:
  email:
    - sfiso.dlaba@gmail.com
services:
  - postgresql
