version: 1.0.{build}
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/identity-postgresql/api/v2/package/
  api_key:
    secure: 6FUgwWE+SbScs3FSO59HSkQMlApDmYKeIHdVgwgvvDggtzYa+We875daTsQzDEaT3SgmnPlblq/vLKRgaFuAZ5FpKqUc6Mbbq5rbQfNZ7mM=
  skip_symbols: true